# Generated by Django 4.0.10 on 2023-05-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_os_device_os_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='desktop',
            new_name='is_desktop',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='mobile',
            new_name='is_mobile',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='tablet',
            new_name='is_tablet',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='os',
            new_name='system_name',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='os_version',
            new_name='system_version',
        ),
        migrations.AddField(
            model_name='device',
            name='total_memory',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
