# Generated by Django 4.0.10 on 2023-06-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_rename_name_device_name_on_device_device_name_in_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconnection',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='deviceconnection',
            name='ip_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deviceconnection',
            name='network_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deviceconnection',
            name='node_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
