# Generated by Django 4.0.10 on 2023-04-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthstate',
            name='access_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='code_verifier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='expires_in',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='re_public_user_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='refresh_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='scope',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='wallet_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
