# Generated by Django 4.0.10 on 2023-04-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_alter_oauthstate_access_token_alter_oauthstate_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='re_public_store_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
