# Generated by Django 4.0.10 on 2023-04-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0003_oauthstate_re_public_store_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
