# Generated by Django 4.0.10 on 2023-04-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0005_oauthstate_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthstate',
            name='expires_in',
        ),
        migrations.AddField(
            model_name='oauthstate',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
