# Generated by Django 4.0.10 on 2023-04-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0006_remove_oauthstate_expires_in_oauthstate_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthstate',
            name='code',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
