# Generated by Django 4.0.10 on 2023-04-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0011_alter_oauthstate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthstate',
            name='code',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
