# Generated by Django 4.0.10 on 2023-05-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0013_rawfileingest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('republic_id', models.CharField(max_length=255, unique=True)),
                ('is_installed', models.BooleanField(default=False)),
                ('is_activated', models.BooleanField(default=False)),
                ('version_number', models.CharField(max_length=10, null=True)),
                ('build_number', models.CharField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
