# Generated by Django 4.0.10 on 2023-10-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0014_connector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='is_activated',
        ),
        migrations.AddField(
            model_name='connector',
            name='repo_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
