# Generated by Django 4.0.10 on 2023-10-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0016_remove_connector_is_activated_connector_repo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
