# Generated by Django 4.0.10 on 2023-10-01 01:20

from django.db import migrations, models
import republic_os.connectors.models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0017_connector_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='svg',
            field=models.FileField(null=True, upload_to='media', validators=[republic_os.connectors.models.validate_file_extension]),
        ),
    ]
