# Generated by Django 4.0.10 on 2023-10-01 01:22

from django.db import migrations, models
import republic_os.connectors.models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0018_connector_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='build_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='repo_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='media', validators=[republic_os.connectors.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='connector',
            name='version_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
