# Generated by Django 4.0.10 on 2023-10-01 01:23

from django.db import migrations, models
import republic_os.connectors.models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0019_alter_connector_build_number_alter_connector_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='connectors'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='connectors', validators=[republic_os.connectors.models.validate_file_extension]),
        ),
    ]
