# Generated by Django 4.0.10 on 2023-10-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0020_alter_connector_image_alter_connector_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthstate',
            name='connector_id',
        ),
        migrations.AddField(
            model_name='connector',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oauthstate',
            name='connector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connectors.connector', to_field='republic_id'),
        ),
    ]
