# Generated by Django 4.0.10 on 2023-10-21 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0024_remove_oauthstate_connector'),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectorsync',
            name='oauth_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='oauth.oauthstate'),
        ),
        migrations.DeleteModel(
            name='OAuthState',
        ),
    ]
