# Generated by Django 4.0.10 on 2023-11-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0025_alter_connectorsync_oauth_state_delete_oauthstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorsync',
            name='task_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
