# Generated by Django 4.0.10 on 2023-11-22 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0026_connectorsync_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorsync',
            name='connector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='syncs', to='connectors.connector'),
        ),
    ]
