# Generated by Django 4.0.10 on 2023-10-21 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectors', '0024_remove_oauthstate_connector'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=500, null=True)),
                ('code', models.CharField(max_length=600, null=True)),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('refresh_token', models.CharField(max_length=255, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('wallet_address', models.CharField(max_length=255, null=True)),
                ('re_public_user_id', models.CharField(max_length=255, null=True)),
                ('code_verifier', models.CharField(max_length=255, null=True)),
                ('re_public_store_token', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
                ('connector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connectors.connector', to_field='republic_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
