# Generated by Django 4.0.10 on 2023-10-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0025_alter_connectorsync_oauth_state_delete_oauthstate'),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='sync_interval_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='connector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauths', to='connectors.connector', to_field='republic_id'),
        ),
    ]
