# Generated by Django 4.0.10 on 2023-04-01 15:25

from django.db import migrations


def seed_data(apps, schema_editor):
    AppInstall = apps.get_model('apps', 'AppInstall')
    AppInstall.objects.create(app_name='Streamr Node', status='not installed', app_id='streamr_node')
    AppInstall.objects.create(app_name='Perkeep', status='not installed', app_id='perkeep')


def reverse_data(apps, schema_editor):
    AppInstall = apps.get_model('apps', 'AppInstall')
    AppInstall.objects.filter(app_id='streamr_node').delete()
    AppInstall.objects.filter(app_id='perkeep').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_data),
    ]
