# Generated by Django 4.0.10 on 2023-04-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20230401_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppInstall',
            new_name='App',
        ),
    ]
