# Generated by Django 4.0.10 on 2023-04-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_appinstall_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='status',
        ),
        migrations.AddField(
            model_name='app',
            name='single_install',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AppInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.app')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
