# Generated by Django 4.0.10 on 2023-04-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_app_status_app_single_install_appinstall'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='price_usd',
            field=models.FloatField(null=True),
        ),
    ]
