# Generated by Django 4.0.10 on 2023-04-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_app_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
