# Generated by Django 4.0.10 on 2023-04-01 16:42

from django.db import migrations, models
import republic_os.apps.models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_app_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='image',
            field=models.ImageField(null=True, upload_to='', validators=[republic_os.apps.models.validate_file_extension]),
        ),
    ]
