# Generated by Django 4.0.10 on 2023-04-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_app_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
