# Generated by Django 4.0.10 on 2023-04-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_app_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='app_id',
            new_name='app_store_id',
        ),
    ]
