# Generated by Django 4.0.10 on 2023-04-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_appinstall_app_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstall',
            name='app',
        ),
    ]
