CONNECTOR_ID_BASE = 'io.re-public.connector'

CONNECTOR_ID_SPOTIFY = f'{CONNECTOR_ID_BASE}.spotify'
CONNECTOR_ID_STRAVA = f'{CONNECTOR_ID_BASE}.strava'
CONNECTOR_ID_GOOGLE = f'{CONNECTOR_ID_BASE}.google'
CONNECTOR_ID_AMAZON = f'{CONNECTOR_ID_BASE}.amazon'
