# Generated by Django 4.0.10 on 2023-04-02 22:10
import os

from django.db import migrations


def seed_data(apps, schema_editor):
    User = apps.get_model('users', 'User')

    try:

        user = User.objects.get(username='admin')

        if user:
            return None

    except User.DoesNotExist:
        pass

    User.objects.create(
        username='admin',
        email=os.environ.get('DJANGO_SUPERUSER_EMAIL'),
        password=os.environ.get('DJANGO_SUPERUSER_PASSWORD'),
        is_staff=True,
        is_superuser=True
    )


def reverse_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_data),
    ]
