# Generated by Django 4.0.10 on 2023-04-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230402_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='re_public_session_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
